# the most basic commands for creating, updating, and activating an environment are:
# conda env create -n loan-etl -f environment.yml
# conda env update -n loan-etl -f environment.yml
# conda activate loan-etl

name: loan-etl
channels:
  - conda-forge
dependencies:
  - python==3.7
  - click==7.0
  - jupyter==1.0.0
  - pandas==0.24.2
  - pip==10.0.1
  - python-json-logger==0.1.10
  - python-dateutil==2.7.3
  - requests==2.19.1
  - setuptools==40.4.3
  - behave==1.2.6
  - sqlalchemy==1.3.5